# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'placeSearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for placeSearch
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'AlamofireImage'
  pod 'EasyToast'
  pod 'SwiftSpinner'
  pod 'McPicker'
  pod 'Cosmos'

  target 'placeSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'placeSearchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
